name: Main Branch Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Install PHP and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install php php-mbstring php-xml

    - name: Install Composer dependencies
      run: composer install --no-interaction --prefer-dist --optimize-autoloader

    - name: Deploy to Server - Main Branche
      run: |
        rsync -avz --delete ./ ${{ secrets.SERVER_USERNAME }}:${{ secrets.SERVER_PASSWORD }}@${{ secrets.SERVER_HOST }}:"/home/meta/domains/meta.serv00.net/public_html/chatapp"
        ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} "cd /home/meta/domains/meta.serv00.net/public_html/chatapp &&\
         composer2 update && \
         php artisan config:cache && \
         php artisan route:cache"
