name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh/
        ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Deploy to Server
      run: |
        sshpass -p "${{ secrets.SERVER_PASSWORD }}" rsync -avz ./ ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/home/meta/domains/meta.serv00.net/public_html/chatapp
        sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} 'cd /home/meta/domains/meta.serv00.net/public_html/chatapp&& composer install --no-interaction --prefer-dist --optimize-autoloader && php artisan config:cache && php artisan route:cache'
